export const NAMES_99 = [
    { no: 1, ar: "ٱلرَّحْمَٰنُ", tr: "Ar-Raḥmān", en: "The Most or Entirely Merciful" },
    { no: 2, ar: "ٱلرَّحِيمُ", tr: "Ar-Raḥīm", en: "The Especially Merciful" },
    { no: 3, ar: "ٱلْمَلِكُ", tr: "Al-Malik", en: "The King and Owner of Dominion" },
    { no: 4, ar: "ٱلْقُدُّوسُ", tr: "Al-Quddūs", en: "The Absolutely Pure and Perfect" },
    { no: 5, ar: "ٱلسَّلَامُ", tr: "As-Salām", en: "The Perfection and Giver of Peace" },
    { no: 6, ar: "ٱلْمُؤْمِنُ", tr: "Al-Mu’min", en: "The Granter of Security and Faith" },
    { no: 7, ar: "ٱلْمُهَيْمِنُ", tr: "Al-Muhaymin", en: "The Guardian, The Witness, The Overseer" },
    { no: 8, ar: "ٱلْعَزِيزُ", tr: "Al-‘Azīz", en: "The Almighty, The All-Powerful, The Invincible, The Honorable" },
    { no: 9, ar: "ٱلْجَبَّارُ", tr: "Al-Jabbār", en: "The Compeller, The Restorer" },
    { no: 10, ar: "ٱلْمُتَكَبِّرُ", tr: "Al-Mutakabbir", en: "The Supreme, The Majestic" },

    { no: 11, ar: "ٱلْخَٰلِقُ", tr: "Al-Khāliq", en: "The Creator, The Maker" },
    { no: 12, ar: "ٱلْبَارِئُ", tr: "Al-Bāriʾ", en: "The Originator, The Inventor" },
    { no: 13, ar: "ٱلْمُصَوِّرُ", tr: "Al-Muṣawwir", en: "The Fashioner, The Shaper" },
    { no: 14, ar: "ٱلْغَفَّارُ", tr: "Al-Ghaffār", en: "The Constant Forgiver, The Great Forgiver" },
    { no: 15, ar: "ٱلْقَهَّارُ", tr: "Al-Qahhār", en: "The Subduer, The Ever-Dominating" },
    { no: 16, ar: "ٱلْوَهَّابُ", tr: "Al-Wahhāb", en: "The Giver of Gifts, The Bestower" },
    { no: 17, ar: "ٱلرَّزَّاقُ", tr: "Ar-Razzāq", en: "The Ever-Providing, The Constant Provider" },
    { no: 18, ar: "ٱلْفَتَّاحُ", tr: "Al-Fattāḥ", en: "The Opener, The Judge" },
    { no: 19, ar: "ٱلْعَلِيمُ", tr: "Al-ʿAlīm", en: "The All-Knowing, The Omniscient" },
    { no: 20, ar: "ٱلْقَابِضُ", tr: "Al-Qābiḍ", en: "The Withholder, The Restrainer" },

    { no: 21, ar: "ٱلْبَاسِطُ", tr: "Al-Bāsiṭ", en: "The Extender, The Expander" },
    { no: 22, ar: "ٱلْخَافِضُ", tr: "Al-Khāfiḍ", en: "The Reducer, The Abaser" },
    { no: 23, ar: "ٱلرَّافِعُ", tr: "Ar-Rāfiʿ", en: "The Exalter, The Elevator" },
    { no: 24, ar: "ٱلْمُعِزُّ", tr: "Al-Muʿizz", en: "The Honourer, The Bestower of Honor" },
    { no: 25, ar: "ٱلْمُذِلُّ", tr: "Al-Mudhill", en: "The Dishonourer, The Humiliator" },
    { no: 26, ar: "ٱلسَّمِيعُ", tr: "As-Samīʿ", en: "The All-Hearing" },
    { no: 27, ar: "ٱلْبَصِيرُ", tr: "Al-Baṣīr", en: "The All-Seeing" },
    { no: 28, ar: "ٱلْحَكَمُ", tr: "Al-Ḥakam", en: "The Judge, The Giver of Justice" },
    { no: 29, ar: "ٱلْعَدْلُ", tr: "Al-‘Adl", en: "The Utterly Just" },
    { no: 30, ar: "ٱللَّطِيفُ", tr: "Al-Laṭīf", en: "The Most Gentle, The Subtle One" },

    { no: 31, ar: "ٱلْخَبِيرُ", tr: "Al-Khabīr", en: "The All-Aware, The All-Acquainted" },
    { no: 32, ar: "ٱلْحَلِيمُ", tr: "Al-Ḥalīm", en: "The Most Forbearing" },
    { no: 33, ar: "ٱلْعَظِيمُ", tr: "Al-ʿAẓīm", en: "The Magnificent, The Supreme" },
    { no: 34, ar: "ٱلْغَفُورُ", tr: "Al-Ghafūr", en: "The Forgiving, The Exceedingly Forgiving" },
    { no: 35, ar: "ٱلشَّكُورُ", tr: "Ash-Shakūr", en: "The Most Appreciative" },
    { no: 36, ar: "ٱلْعَلِيُّ", tr: "Al-ʿAlī", en: "The Most High, The Exalted" },
    { no: 37, ar: "ٱلْكَبِيرُ", tr: "Al-Kabīr", en: "The Greatest, The Most Grand" },
    { no: 38, ar: "ٱلْحَفِيظُ", tr: "Al-Ḥafīẓ", en: "The Preserver, The All-Heedful and All-Protecting" },
    { no: 39, ar: "ٱلْمُقِيتُ", tr: "Al-Muqīt", en: "The Sustainer, The Maintainer" },
    { no: 40, ar: "ٱلْحَسِيبُ", tr: "Al-Ḥasīb", en: "The Reckoner" },

    { no: 41, ar: "ٱلْجَلِيلُ", tr: "Al-Jalīl", en: "The Majestic" },
    { no: 42, ar: "ٱلْكَرِيمُ", tr: "Al-Karīm", en: "The Most Generous, The Most Noble" },
    { no: 43, ar: "ٱلرَّقِيبُ", tr: "Ar-Raqīb", en: "The Watchful, The All-Watchful" },
    { no: 44, ar: "ٱلْمُجِيبُ", tr: "Al-Mujīb", en: "The Responsive, The Answerer" },
    { no: 45, ar: "ٱلْوَاسِعُ", tr: "Al-Wāsiʿ", en: "The All-Encompassing, the Boundless" },
    { no: 46, ar: "ٱلْحَكِيمُ", tr: "Al-Ḥakīm", en: "The All-Wise" },
    { no: 47, ar: "ٱلْوَدُودُ", tr: "Al-Wadūd", en: "The Most Loving" },
    { no: 48, ar: "ٱلْمَجِيدُ", tr: "Al-Majīd", en: "The Glorious, The Most Honorable" },
    { no: 49, ar: "ٱلْبَاعِثُ", tr: "Al-Bāʿith", en: "The Infuser of New Life, The Resurrector" },
    { no: 50, ar: "ٱلشَّهِيدُ", tr: "As-Shahīd", en: "The All-Witnessing" },

    { no: 51, ar: "ٱلْحَقُّ", tr: "Al-Ḥaqq", en: "The Absolute Truth" },
    { no: 52, ar: "ٱلْوَكِيلُ", tr: "Al-Wakīl", en: "The Trustee, The Disposer of Affairs" },
    { no: 53, ar: "ٱلْقَوِيُّ", tr: "Al-Qawiyy", en: "The All-Strong" },
    { no: 54, ar: "ٱلْمَتِينُ", tr: "Al-Matīn", en: "The Firm, The Steadfast" },
    { no: 55, ar: "ٱلْوَلِيُّ", tr: "Al-Waliyy", en: "The Protector, The Guardian" },
    { no: 56, ar: "ٱلْحَمِيدُ", tr: "Al-Ḥamīd", en: "The Praiseworthy, The Most Praised" },
    { no: 57, ar: "ٱلْمُحْصِي", tr: "Al-Muḥṣī", en: "The All-Enumerating, The Counter" },
    { no: 58, ar: "ٱلْمُبْدِئُ", tr: "Al-Mubdiʾ", en: "The Originator, The Initiator" },
    { no: 59, ar: "ٱلْمُعِيدُ", tr: "Al-Muʿīd", en: "The Restorer, The Reinstater" },
    { no: 60, ar: "ٱلْمُحْيِي", tr: "Al-Muḥyī", en: "The Giver of Life" },

    { no: 61, ar: "ٱلْمُمِيتُ", tr: "Al-Mumīt", en: "The Creator of Death" },
    { no: 62, ar: "ٱلْحَيُّ", tr: "Al-Ḥayy", en: "The Ever-Living" },
    { no: 63, ar: "ٱلْقَيُّومُ", tr: "Al-Qayyūm", en: "The Sustainer, The Self-Subsisting" },
    { no: 64, ar: "ٱلْوَاجِدُ", tr: "Al-Wājid", en: "The Finder, The Perceiver" },
    { no: 65, ar: "ٱلْمَاجِدُ", tr: "Al-Mājid", en: "The Illustrious, The Magnificent" },
    { no: 66, ar: "ٱلْوَاحِدُ", tr: "Al-Wāḥid", en: "The One, The Indivisible" },
    { no: 67, ar: "ٱلْأَحَدُ", tr: "Al-Aḥad", en: "The Unique, The Only One" },
    { no: 68, ar: "ٱلصَّمَدُ", tr: "Aṣ-Ṣamad", en: "The Eternal, The Absolute" },
    { no: 69, ar: "ٱلْقَادِرُ", tr: "Al-Qādir", en: "The Omnipotent, The All-Able" },
    { no: 70, ar: "ٱلْمُقْتَدِرُ", tr: "Al-Muqtadir", en: "The All-Powerful, The Dominant" },

    { no: 71, ar: "ٱلْمُقَدِّمُ", tr: "Al-Muqaddim", en: "The Expediter, The Promoter" },
    { no: 72, ar: "ٱلْمُؤَخِّرُ", tr: "Al-Muʾakhkhir", en: "The Delayer, The Postponer" },
    { no: 73, ar: "ٱلْأَوَّلُ", tr: "Al-Awwal", en: "The First, The Foremost" },
    { no: 74, ar: "ٱلْآخِرُ", tr: "Al-Ākhir", en: "The Last, The Utmost" },
    { no: 75, ar: "ٱلظَّاهِرُ", tr: "Aẓ-Ẓāhir", en: "The Manifest, The All-Surpassing" },
    { no: 76, ar: "ٱلْبَاطِنُ", tr: "Al-Bāṭin", en: "The Hidden One, Knower of the Hidden" },
    { no: 77, ar: "ٱلْوَالِي", tr: "Al-Wālī", en: "The Sole Governor" },
    { no: 78, ar: "ٱلْمُتَعَالِي", tr: "Al-Mutaʿālī", en: "The Self-Exalted" },
    { no: 79, ar: "ٱلْبَرُّ", tr: "Al-Barr", en: "The Source of All Goodness" },
    { no: 80, ar: "ٱلتَّوَابُ", tr: "At-Tawwāb", en: "The Ever-Pardoning" },

    { no: 81, ar: "ٱلْمُنْتَقِمُ", tr: "Al-Muntaqim", en: "The Avenger" },
    { no: 82, ar: "ٱلْعَفُوُّ", tr: "Al-ʿAfūw", en: "The Pardoner" },
    { no: 83, ar: "ٱلرَّءُوفُ", tr: "Ar-Raʾūf", en: "The Most Kind" },
    { no: 84, ar: "مَالِكُ ٱلْمُلْكِ", tr: "Mālik al-Mulk", en: "Master of the Dominion, Owner of the Kingdom" },
    { no: 85, ar: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ", tr: "Dhū al-Jalāli wa’l-Ikrām", en: "Possessor of Glory and Honour" },
    { no: 86, ar: "ٱلْمُقْسِطُ", tr: "Al-Muqsiṭ", en: "The Just One" },
    { no: 87, ar: "ٱلْجَامِعُ", tr: "Al-Jāmiʿ", en: "The Gatherer, the Uniter" },
    { no: 88, ar: "ٱلْغَنِيُّ", tr: "Al-Ghaniyy", en: "The Self-Sufficient, The Wealthy" },
    { no: 89, ar: "ٱلْمُغْنِيُ", tr: "Al-Mughnī", en: "The Enricher" },
    { no: 90, ar: "ٱلْمَانِعُ", tr: "Al-Māniʿ", en: "The Withholder" },

    { no: 91, ar: "ٱلضَّارُّ", tr: "Aḍ-Ḍārr", en: "The Distresser" },
    { no: 92, ar: "ٱلنَّافِعُ", tr: "An-Nāfiʿ", en: "The Propitious, The Benefactor" },
    { no: 93, ar: "ٱلنُّورُ", tr: "An-Nūr", en: "The Light" },
    { no: 94, ar: "ٱلْهَادِي", tr: "Al-Hādī", en: "The Guide" },
    { no: 95, ar: "ٱلْبَدِيعُ", tr: "Al-Badīʿ", en: "The Incomparable Originator" },
    { no: 96, ar: "ٱلْبَاقِي", tr: "Al-Bāqī", en: "The Ever-Lasting" },
    { no: 97, ar: "ٱلْوَارِثُ", tr: "Al-Wāriṯ", en: "The Inheritor" },
    { no: 98, ar: "ٱلرَّشِيدُ", tr: "Ar-Rashīd", en: "The Guide to the Right Path" },
    { no: 99, ar: "ٱلصَّبُورُ", tr: "Aṣ-Ṣabūr", en: "The Patient" },
];
